// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvN0zKFrX2s365aTbIMSa4kepmICEDho4',
    appId: '1:342492431923:web:0aae2cf2112271f9088546',
    messagingSenderId: '342492431923',
    projectId: 'flutter-e0b09',
    authDomain: 'flutter-e0b09.firebaseapp.com',
    storageBucket: 'flutter-e0b09.firebasestorage.app',
    measurementId: 'G-JYW19DMN0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3HF74hn9ClVYdWVkTNXU_L-qMM7qmitg',
    appId: '1:342492431923:android:56bd853134feab98088546',
    messagingSenderId: '342492431923',
    projectId: 'flutter-e0b09',
    storageBucket: 'flutter-e0b09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKjqCzZAQnBjEVBjyzy_nQiyoIx1nmbc',
    appId: '1:342492431923:ios:ba4329309af96b96088546',
    messagingSenderId: '342492431923',
    projectId: 'flutter-e0b09',
    storageBucket: 'flutter-e0b09.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKjqCzZAQnBjEVBjyzy_nQiyoIx1nmbc',
    appId: '1:342492431923:ios:ba4329309af96b96088546',
    messagingSenderId: '342492431923',
    projectId: 'flutter-e0b09',
    storageBucket: 'flutter-e0b09.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvN0zKFrX2s365aTbIMSa4kepmICEDho4',
    appId: '1:342492431923:web:23868f7d95a825c3088546',
    messagingSenderId: '342492431923',
    projectId: 'flutter-e0b09',
    authDomain: 'flutter-e0b09.firebaseapp.com',
    storageBucket: 'flutter-e0b09.firebasestorage.app',
    measurementId: 'G-9S0EQPGVTB',
  );
}
